### ISSUE TITLE
CKAN dependency for Parallax broken

### ISSUE THREAD

**Issue by georgedorn** [Gameslinx/BeyondHomePlanetMod#17]
Beyond Home's CKAN metadata appears to insist on Parallax v1.0.1, and there doesn't seem to be a way to install Parallax 1.3.0 + Beyond Home via CKAN.

This is all on KSP 1.12.1, which both Kopernicus and Parallax 1.3.0 supports.  I haven't yet tested manually installing Parallax (will update this issue when I do) but maybe the BH metadata just needs an update?

**Comment by DasSkelett** [comment]
Please report CKAN metadata problems in [CKAN's repository](https://github.com/KSP-CKAN/NetKAN), do NOT bother mod authors with them. We, the CKAN team, are the ones responsible for maintaining the metadata, we are the ones who need to know about metadata issues. In most cases mod authors can't help you.

That aside, yes, CKAN does strictly require Parallax 1.0.1 for BeyondHome 1.5.2. This is enforced to follow the instructions on the forum thread:
![image](https://user-images.githubusercontent.com/28812678/126050639-20582483-3663-428e-ad52-01ef65c1be1d.png)

**Comment by georgedorn** [comment]
Given that Gameslinx maintains both mods in question, the author might have more insight here.

**Comment by DasSkelett** [comment]
The metadata is still maintained by the CKAN team, so please make sure to report future CKAN problems to us. If it's indeed not something the CKAN team can fix, or we need more information ourselves, we can still redirect to / ask the author afterwards.

But yes, if the statement on the forum thread is for some reason no longer true (I doubt that), Gameslinx is the one who can tell us.

**Comment by georgedorn** [comment]
After a few go-rounds on this, 1.0.1 is the right Parallax, with the right additional patches and config edits for linux.  The biggest annoyance is CKAN constantly trying to upgrade Parallax to the latest, even with the version pinned, but I can live with it until this mod is updated again.
